---
# Name:      PyHouse/Project/admin/config/Yaml/main.yaml
# Author:    D. Brian Kimmel
# Contact:   D.BrianKimmel@gmail.com
# Copyright: (c)2019-2019 by D. Brian Kimmel
# Created:   Jun 10, 2019
# Updated:   Jun 20, 2019
# License:   MIT License
# Summary:   This is for PyHouse

PyHouse:
   Name: cannon trail
   UnitSystem: metric
   ConfigVersion: 2.0

# Computer: !include computer/modules.yaml
# House: !include house/house.yaml

### END DBK
