"""
-*- test-case-name: /home/briank/PyHouse/src/Modules/Housing/Security/test/xml_motion_sensors.py -*-

@name:      /home/briank/PyHouse/src/Modules/Housing/Security/test/xml_motion_sensors.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2016-2017 by D. Brian Kimmel
@note:      Created on Nov 1, 2016
@license:   MIT License
@summary:

"""

__updated__ = '2016-11-01'

# Import system type stuff

# Import PyMh files


L_MOTION_SENSOR_SECTION_START = '<MotionDetectorSection>'
L_MOTION_SENSOR_SECTION_END = '</MotionDetectorSection>'
L_MOTION_SENSOR_END = '</Motion>'

TESTING_MOTION_SENSOR_NAME_0 = 'Insteon Motion Detector'
TESTING_MOTION_SENSOR_ACTIVE_0 = 'True'
TESTING_MOTION_SENSOR_KEY_0 = '0'
TESTING_MOTION_SENSOR_UUID_0 = 'Motion..-0000-0000-0000-0123456789ab'
TESTING_MOTION_SENSOR_COMMENT_0 = "Motion Detector Comment"
TESTING_MOTION_SENSOR_DEVCAT_0 = '04.20'
TESTING_MOTION_SENSOR_DEVICE_FAMILY_0 = 'Insteon'
TESTING_MOTION_SENSOR_DEVICE_TYPE_0 = '3'
TESTING_MOTION_SENSOR_DEVICE_SUBTYPE_0 = '2'
TESTING_MOTION_SENSOR_ROOM_X = '1.23'
TESTING_MOTION_SENSOR_ROOM_Y = '4.56'
TESTING_MOTION_SENSOR_ROOM_Z = '7.89'
TESTING_MOTION_SENSOR_ROOM_COORDS_0 = '[1.23, 4.56, 7.89]'
TESTING_MOTION_SENSOR_ROOM_NAME_0 = 'LivingRoom'
TESTING_MOTION_SENSOR_ROOM_UUID_0 = 'LR......-Room-0000-0000-Room.8b6eb6f'

L_MOTION_SENSOR_START_0 = \
        '<Motion Name="' + TESTING_MOTION_SENSOR_NAME_0 + \
        '" Key="' + TESTING_MOTION_SENSOR_KEY_0 + \
        '" Active="' + TESTING_MOTION_SENSOR_ACTIVE_0 + \
        '">'
L_MOTION_SENSOR_UUID_0 = '    <UUID>' + TESTING_MOTION_SENSOR_UUID_0 + '</UUID>'
L_MOTION_SENSOR_COMMENT_0 = '    <Comment>' + TESTING_MOTION_SENSOR_COMMENT_0 + '</Comment>'
L_MOTION_SENSOR_DEVCAT_0 = '    <DevCat>' + TESTING_MOTION_SENSOR_DEVCAT_0 + '</DevCat>'
L_MOTION_SENSOR_DEVICE_TYPE_0 = '    <DeviceType>' + TESTING_MOTION_SENSOR_DEVICE_TYPE_0 + '</DeviceType>'
L_MOTION_SENSOR_DEVICE_SUBTYPE_0 = '    <DeviceSubType>' + TESTING_MOTION_SENSOR_DEVICE_SUBTYPE_0 + '</DeviceSubType>'
L_MOTION_SENSOR_ROOM_COORDS_0 = '    <RoomCoords>' + TESTING_MOTION_SENSOR_ROOM_COORDS_0 + '</RoomCoords>'
L_MOTION_SENSOR_ROOM_NAME_0 = '    <RoomName>' + TESTING_MOTION_SENSOR_ROOM_NAME_0 + '</RoomName>'
L_MOTION_SENSOR_ROOM_UUID_0 = '    <RoomUUID>' + TESTING_MOTION_SENSOR_ROOM_UUID_0 + '</RoomUUID>'

L_MOTION_SENSOR_DEVICE_FAMILY_0 = "    <DeviceFamily>" + TESTING_MOTION_SENSOR_DEVICE_FAMILY_0 + "</DeviceFamily>"



L_MOTION_SENSOR_BODY = '\n'.join([
    L_MOTION_SENSOR_COMMENT_0,
    L_MOTION_SENSOR_DEVICE_FAMILY_0,
    L_MOTION_SENSOR_DEVICE_TYPE_0,
    L_MOTION_SENSOR_DEVICE_SUBTYPE_0,
    L_MOTION_SENSOR_ROOM_COORDS_0,
    L_MOTION_SENSOR_ROOM_NAME_0,
    L_MOTION_SENSOR_ROOM_UUID_0,
    L_MOTION_SENSOR_UUID_0
    ])

TESTING_MOTION_SENSOR_ADDRESS_0 = '37.AD.0A'
TESTING_MOTION_SENSOR_DEVCAT_0 = '05.1C'
TESTING_MOTION_SENSOR_ENGINE_VERSION_0 = '1'
TESTING_MOTION_SENSOR_FIRMWARE_VERSION_0 = '32'
TESTING_MOTION_SENSOR_GROUP_NUM_0 = '0'
TESTING_MOTION_SENSOR_GROUP_LIST_0 = 'All_Lights'
TESTING_MOTION_SENSOR_PRODUCT_KEY_0 = '21.22.23'
TESTING_MOTION_SENSOR_LINKS_0 = {}

L_MOTION_SENSOR_ADDRESS_0 = '    <InsteonAddress>' + TESTING_MOTION_SENSOR_ADDRESS_0 + '</InsteonAddress>'
L_MOTION_SENSOR_DEVCAT_0 = '    <DevCat>' + TESTING_MOTION_SENSOR_DEVCAT_0 + '</DevCat>'
L_MOTION_SENSOR_ENGINE_VERSION_0 = '    <EngineVersion>' + TESTING_MOTION_SENSOR_ENGINE_VERSION_0 + '</EngineVersion>'
L_MOTION_SENSOR_FIRMWARE_VERSION_0 = '    <FirmwareVersion>' + TESTING_MOTION_SENSOR_FIRMWARE_VERSION_0 + '</FirmwareVersion>'
L_MOTION_SENSOR_GROUP_NUM_0 = '    <GroupNumber>' + TESTING_MOTION_SENSOR_GROUP_NUM_0 + '</GroupNumber>'
L_MOTION_SENSOR_GROUP_LIST_0 = '    <GroupList>' + TESTING_MOTION_SENSOR_GROUP_LIST_0 + '</GroupList>'
L_MOTION_SENSOR_PRODUCT_KEY_0 = '    <ProductKey>' + TESTING_MOTION_SENSOR_PRODUCT_KEY_0 + '</ProductKey>'

XML_MOTION_SENSOR_0 = '\n'.join([
    L_MOTION_SENSOR_ADDRESS_0,
    L_MOTION_SENSOR_DEVCAT_0,
    L_MOTION_SENSOR_ENGINE_VERSION_0,
    L_MOTION_SENSOR_FIRMWARE_VERSION_0,
    L_MOTION_SENSOR_GROUP_NUM_0,
    L_MOTION_SENSOR_GROUP_LIST_0,
    L_MOTION_SENSOR_PRODUCT_KEY_0,
    ])

XML_INSTEON_MOTION = '\n'.join([
    L_MOTION_SENSOR_START_0,
    L_MOTION_SENSOR_BODY,
    XML_MOTION_SENSOR_0,
    L_MOTION_SENSOR_END
    ])

XML_MOTION_SENSOR_SECTION = '\n'.join([
    L_MOTION_SENSOR_SECTION_START,
    XML_INSTEON_MOTION,
    L_MOTION_SENSOR_SECTION_END
    ])

# ## END DBK
