"""
@name:      PyHouse/src/Modules/Housing/Entertainment/panasonic/_test/xml_panasonic.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2018-2018 by D. Brian Kimmel
@note:      Created on Aug 10, 2018
@license:   MIT License
@summary:

<EntertainmentSection>
    <PanasonicSection Active="False" />
</EntertainmentSection>
"""

__updated__ = '2018-08-17'

TESTING_PANASONIC_SECTION = 'PanasonicSection'
TESTING_DEVICE = 'Device'
TESTING_PANASONIC_ACTIVE = 'False'
TESTING_PANASONIC_TYPE = 'Component'

TESTING_PANASONIC_DEVICE_NAME_0 = 'L/R Receiver TX-555'
TESTING_PANASONIC_DEVICE_KEY_0 = '0'
TESTING_PANASONIC_DEVICE_ACTIVE_0 = 'True'
TESTING_PANASONIC_DEVICE_UUID_0 = 'Panasoni-c000-0000-0000-0123456789ab'
TESTING_PANASONIC_DEVICE_COMMENT_0 = 'Tx-555 Receiver'
TESTING_PANASONIC_DEVICE_IPV4_0 = '192.168.1.138'
TESTING_PANASONIC_DEVICE_PORT_0 = '60128'
TESTING_PANASONIC_DEVICE_ROOM_NAME_0 = 'Living Room'
TESTING_PANASONIC_DEVICE_ROOM_UUID_0 = 'Room....-0000-0000-0000-0123456789ab'
TESTING_PANASONIC_DEVICE_TYPE_0 = 'Receiver'
TESTING_PANASONIC_DEVICE_VOLUME_0 = '42'

L_PANASONIC_SECTION_START = '<' + TESTING_PANASONIC_SECTION + ' Active="' + TESTING_PANASONIC_ACTIVE + '">'
L_PANASONIC_SECTION_END = '</' + TESTING_PANASONIC_SECTION + '>'
L_DEVICE_END = '</' + TESTING_DEVICE + '>'
L_PANASONIC_SECTION_TYPE = '<Type>' + TESTING_PANASONIC_TYPE + '</Type>'
L_PANASONIC_DEVICE_START_0 = \
    '<' + TESTING_DEVICE + \
    ' Name="' + TESTING_PANASONIC_DEVICE_NAME_0 + \
    '" Key="' + TESTING_PANASONIC_DEVICE_KEY_0 + \
    '" Active="' + TESTING_PANASONIC_DEVICE_ACTIVE_0 + \
    '">'
L_PANASONIC_UUID_0 = '<UUID>' + TESTING_PANASONIC_DEVICE_UUID_0 + '</UUID>'
L_PANASONIC_COMMENT_0 = '<Comment>' + TESTING_PANASONIC_DEVICE_COMMENT_0 + '</Comment>'
L_PANASONIC_IPV4_0 = '<IPv4>' + TESTING_PANASONIC_DEVICE_IPV4_0 + '</IPv4>'
L_PANASONIC_PORT_0 = '<Port>' + TESTING_PANASONIC_DEVICE_PORT_0 + '</Port>'
L_PANASONIC_ROOM_NAME_0 = '<RoomName>' + TESTING_PANASONIC_DEVICE_ROOM_NAME_0 + '</RoomName>'
L_PANASONIC_ROOM_UUID_0 = '<RoomUUID>' + TESTING_PANASONIC_DEVICE_ROOM_UUID_0 + '</RoomUUID>'
L_PANASONIC_TYPE_0 = '<Type>' + TESTING_PANASONIC_DEVICE_TYPE_0 + '</Type>'
L_PANASONIC_VOLUME_0 = '<Volume>' + TESTING_PANASONIC_DEVICE_VOLUME_0 + '</Volume>'

L_PANASONIC_DEVICE_0 = '\n'.join([
    L_PANASONIC_DEVICE_START_0,
    L_PANASONIC_UUID_0,
    L_PANASONIC_COMMENT_0,
    L_PANASONIC_IPV4_0,
    L_PANASONIC_PORT_0,
    L_PANASONIC_ROOM_NAME_0,
    L_PANASONIC_ROOM_UUID_0,
    L_PANASONIC_TYPE_0,
    L_PANASONIC_VOLUME_0,
    L_DEVICE_END
])

TESTING_PANASONIC_DEVICE_NAME_1 = 'Receiver T2 = X-555'
TESTING_PANASONIC_DEVICE_KEY_1 = '1'
TESTING_PANASONIC_DEVICE_ACTIVE_1 = 'False'
TESTING_PANASONIC_DEVICE_UUID_1 = 'Onkyo...-0000-0001-0001-0123456789ab'
TESTING_PANASONIC_DEVICE_COMMENT_1 = 'Tx-555 Receiver_2'
TESTING_PANASONIC_DEVICE_IPV4_1 = '192.168.1.139'
TESTING_PANASONIC_DEVICE_PORT_1 = '60128'
TESTING_PANASONIC_DEVICE_ROOM_NAME_1 = 'Living Room'
TESTING_PANASONIC_DEVICE_ROOM_UUID_1 = 'Room....-0000-0000-0000-0123456789ab'
TESTING_PANASONIC_DEVICE_TYPE_1 = 'Receiver'
TESTING_PANASONIC_DEVICE_VOLUME_1 = '24'

L_PANASONIC_DEVICE_START_1 = \
    '<' + TESTING_DEVICE + \
    ' Name="' + TESTING_PANASONIC_DEVICE_NAME_1 + \
    '" Key="' + TESTING_PANASONIC_DEVICE_KEY_1 + \
    '" Active="' + TESTING_PANASONIC_DEVICE_ACTIVE_1 + \
    '">'
L_PANASONIC_UUID_1 = '<UUID>' + TESTING_PANASONIC_DEVICE_UUID_1 + '</UUID>'
L_PANASONIC_COMMENT_1 = '<Comment>' + TESTING_PANASONIC_DEVICE_COMMENT_1 + '</Comment>'
L_PANASONIC_IPV4_1 = '<IPv4>' + TESTING_PANASONIC_DEVICE_IPV4_1 + '</IPv4>'
L_PANASONIC_PORT_1 = '<Port>' + TESTING_PANASONIC_DEVICE_PORT_1 + '</Port>'
L_PANASONIC_ROOM_NAME_1 = '<RoomName>' + TESTING_PANASONIC_DEVICE_ROOM_NAME_1 + '</RoomName>'
L_PANASONIC_ROOM_UUID_1 = '<RoomUUID>' + TESTING_PANASONIC_DEVICE_ROOM_UUID_1 + '</RoomUUID>'
L_PANASONIC_TYPE_1 = '<Type>' + TESTING_PANASONIC_DEVICE_TYPE_1 + '</Type>'
L_PANASONIC_VOLUME_1 = '<Volume>' + TESTING_PANASONIC_DEVICE_VOLUME_1 + '</Volume>'

L_PANASONIC_DEVICE_1 = '\n'.join([
    L_PANASONIC_DEVICE_START_1,
    L_PANASONIC_UUID_1,
    L_PANASONIC_COMMENT_1,
    L_PANASONIC_IPV4_1,
    L_PANASONIC_PORT_1,
    L_PANASONIC_ROOM_NAME_1,
    L_PANASONIC_ROOM_UUID_1,
    L_PANASONIC_TYPE_1,
    L_PANASONIC_VOLUME_1,
    L_DEVICE_END
])

XML_PANASONIC_SECTION = '\n'.join([
    L_PANASONIC_SECTION_START,
    L_PANASONIC_SECTION_TYPE,
    L_PANASONIC_DEVICE_0,
    L_PANASONIC_DEVICE_1,
    L_PANASONIC_SECTION_END
])

# ## END DBK
