---
# Name:      Modules/House/Family/Insteon/test/Yaml/insteon.yaml
# Author:    D. Brian Kimmel
# Contact:   D.BrianKimmel@gmail.com
# Copyright: (c)2019-2019 by D. Brian Kimmel
# Created:   Jul  2, 2019
# Updated:   Jul 19, 2019
# License:   MIT License
# Summary:   This is for PyHouse

Insteon:
   Controllers:
      Insteon-Hub:
         Host: insteon-hub-ct
         Port: 25105  # Zenmap 443, 25105 only tcp ports open
         Type: Hub
         Interface: Tcp
      Plm-1:
         Node: pi-01-ct
         Type: Plm
      Plm-2:
         Node: pi-11-ct
         Type: Plm
   Devices:
      - Switch
      - Thermostat
      - Camera
      - Outlet

### END DBK
