"""
@name:      PyHouse/src/Modules/Lighting/test/xml_buttons.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2014-2016 by D. Brian Kimmel
@license:   MIT License
@note:      Created on Nov 22, 2014
@Summary:

"""

__updated__ = '2016-11-01'

# Import system type stuff

# Import PyMh files
from Modules.Core.test.xml_device import XML_DEVICE_INSTEON
from Modules.Families.UPB.test.xml_upb import XML_UPB


L_BUTTON_SECTION_START = '<ButtonSection>'
L_BUTTON_SECTION_END = '</ButtonSection>'
L_LIGHTING_BUTTON_END = '</Button>'

TESTING_LIGHTING_BUTTON_NAME_0 = 'Insteon Button 0'
TESTING_LIGHTING_BUTTON_KEY_0 = '0'
TESTING_LIGHTING_BUTTON_ACTIVE_0 = 'True'
TESTING_LIGHTING_BUTTON_COMMENT_0 = 'Comment Button 0'
TESTING_LIGHTING_BUTTON_DEVICE_SUBTYPE_0 = '1'
TESTING_LIGHTING_BUTTON_DEVICE_TYPE_0 = '1'
TESTING_LIGHTING_BUTTON_FAMILY_0 = 'Insteon'
TESTING_LIGHTING_BUTTON_INSTEON_ADDRESS_0 = '35.6F.2A'
TESTING_LIGHTING_BUTTON_ROOM_X_0 = '3.4'
TESTING_LIGHTING_BUTTON_ROOM_Y_0 = '5.6'
TESTING_LIGHTING_BUTTON_ROOM_Z_0 = '1.2'
TESTING_LIGHTING_BUTTON_ROOM_COORDS_0 = '[' + TESTING_LIGHTING_BUTTON_ROOM_X_0 + ', ' + TESTING_LIGHTING_BUTTON_ROOM_Y_0 + ', ' + TESTING_LIGHTING_BUTTON_ROOM_Z_0 + ']'
TESTING_LIGHTING_BUTTON_ROOM_NAME_0 = "Testing Room Name ABDG"
TESTING_LIGHTING_BUTTON_ROOM_UUID_0 = 'Button..-Room-0001-0002-deadbeef1234'
TESTING_LIGHTING_BUTTON_UUID_0 = 'Button..-Dev.-0001-0002-deadbeef1234'

L_LIGHTING_BUTTON_START_0 = \
        '<Button Name="' + TESTING_LIGHTING_BUTTON_NAME_0 + \
        '" Key="' + TESTING_LIGHTING_BUTTON_KEY_0 + \
        '" Active="' + TESTING_LIGHTING_BUTTON_ACTIVE_0 + \
        '">'
L_LIGHTING_BUTTON_UUID_0 = '    <UUID>' + TESTING_LIGHTING_BUTTON_UUID_0 + '</UUID>'
L_LIGHTING_BUTTON_COMMENT_0 = '    <Comment>' + TESTING_LIGHTING_BUTTON_COMMENT_0 + '</Comment>'
L_LIGHTING_BUTTON_INSTEON_ADDRESS_0 = '    <InsteonAddress>' + TESTING_LIGHTING_BUTTON_INSTEON_ADDRESS_0 + '</InsteonAddress>'
L_LIGHTING_BUTTON_ROOM_COORDS_0 = '    <RoomCoords>' + TESTING_LIGHTING_BUTTON_ROOM_COORDS_0 + '</RoomCoords>'
L_LIGHTING_BUTTON_ROOM_NAME_0 = '    <RoomName>' + TESTING_LIGHTING_BUTTON_ROOM_NAME_0 + '</RoomName>'
L_LIGHTING_BUTTON_ROOM_UUID_0 = '    <RoomUUID>' + TESTING_LIGHTING_BUTTON_ROOM_UUID_0 + '</RoomUUID>'
L_LIGHTING_BUTTON_DEVICE_TYPE_0 = '    <DeviceType>' + TESTING_LIGHTING_BUTTON_DEVICE_TYPE_0 + '</DeviceType>'
L_LIGHTING_BUTTON_DEVICE_SUBTYPE_0 = '    <DeviceSubType>' + TESTING_LIGHTING_BUTTON_DEVICE_SUBTYPE_0 + '</DeviceSubType>'
L_LIGHTING_BUTTON_DEVICE_FAMILY_0 = "    <DeviceFamily>" + TESTING_LIGHTING_BUTTON_FAMILY_0 + "</DeviceFamily>"

L_BUTTON_BODY = '\n'.join([
    XML_DEVICE_INSTEON,
    ])

XML_LIGHTING_BUTTON_0 = '\n'.join([
    L_LIGHTING_BUTTON_START_0,
    L_LIGHTING_BUTTON_UUID_0,
    L_LIGHTING_BUTTON_COMMENT_0,
    L_LIGHTING_BUTTON_INSTEON_ADDRESS_0,
    L_LIGHTING_BUTTON_DEVICE_FAMILY_0,
    L_LIGHTING_BUTTON_DEVICE_TYPE_0,
    L_LIGHTING_BUTTON_DEVICE_SUBTYPE_0,
    L_LIGHTING_BUTTON_ROOM_NAME_0,
    L_LIGHTING_BUTTON_ROOM_COORDS_0,
    L_LIGHTING_BUTTON_ROOM_UUID_0,
    L_LIGHTING_BUTTON_END
    ])

TESTING_LIGHTING_BUTTON_NAME_1 = 'UPB Button'
XML_LIGHTING_BUTTON_1 = '\n'.join([
    '<Button Name="' + TESTING_LIGHTING_BUTTON_NAME_1 + '" Active="True" Key="1">',
    L_BUTTON_BODY,
    XML_UPB,
    L_LIGHTING_BUTTON_END
    ])

XML_BUTTON_SECTION = '\n'.join([
    L_BUTTON_SECTION_START,
    XML_LIGHTING_BUTTON_0,
    XML_LIGHTING_BUTTON_1,
    L_BUTTON_SECTION_END
    ])

# ## END DBK
