"""
-*- test-case-name: /home/briank/workspace/PyHouse/src/Modules/Housing/Entertainment/PIONEER/test/xml_pioneer.py -*-

@name:      /home/briank/workspace/PyHouse/src/Modules/Housing/Entertainment/pioneer/test/xml_pioneer.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2018-2018 by D. Brian Kimmel
@note:      Created on Ju1 19, 2018
@license:   MIT License
@summary:

"""

__updated__ = '2018-07-11'

TESTING_PIONEER_SECTION = 'PioneerSection'
TESTING_DEVICE = 'Device'

L_PIONEER_SECTION_START = '<' + TESTING_PIONEER_SECTION + '>'
L_PIONEER_SECTION_END = '</' + TESTING_PIONEER_SECTION + '>'
L_DEVICE_END = '</' + TESTING_DEVICE + '>'

TESTING_PIONEER_DEVICE_NAME_0 = 'L/R Receiver VSX-822-K'
TESTING_PIONEER_DEVICE_KEY_0 = '0'
TESTING_PIONEER_DEVICE_ACTIVE_0 = 'True'
TESTING_PIONEER_DEVICE_UUID_0 = 'Pioneer.-0000-0000-0000-0123456789ab'
TESTING_PIONEER_DEVICE_COMMENT_0 = 'VSX-822-K Receiver'
TESTING_PIONEER_DEVICE_IPV4_0 = '192.168.1.121'
TESTING_PIONEER_DEVICE_PORT_0 = '8102'
TESTING_PIONEER_DEVICE_ROOM_NAME_0 = 'Living Room'
TESTING_PIONEER_DEVICE_ROOM_UUID_0 = 'Room....-0000-0000-0000-0123456789ab'
TESTING_PIONEER_DEVICE_TYPE_0 = 'Receiver'

L_PIONEER_DEVICE_START_0 = '    ' + \
    '<' + TESTING_DEVICE + \
    ' Name="' + TESTING_PIONEER_DEVICE_NAME_0 + \
    '" Key="' + TESTING_PIONEER_DEVICE_KEY_0 + \
    '" Active="' + TESTING_PIONEER_DEVICE_ACTIVE_0 + \
    '">'
L_PIONEER_UUID_0 = '<UUID>' + TESTING_PIONEER_DEVICE_UUID_0 + '</UUID>'
L_PIONEER_COMMENT_0 = '<Comment>' + TESTING_PIONEER_DEVICE_COMMENT_0 + '</Comment>'
L_PIONEER_IPV4_0 = '<IPv4>' + TESTING_PIONEER_DEVICE_IPV4_0 + '</IPv4>'
L_PIONEER_PORT_0 = '<Port>' + TESTING_PIONEER_DEVICE_PORT_0 + '</Port>'
L_PIONEER_ROOM_NAME_0 = '<RoomName>' + TESTING_PIONEER_DEVICE_ROOM_NAME_0 + '</RoomName>'
L_PIONEER_ROOM_UUID_0 = '<RoomUUID>' + TESTING_PIONEER_DEVICE_ROOM_UUID_0 + '</RoomUUID>'
L_PIONEER_TYPE_0 = '<Type>' + TESTING_PIONEER_DEVICE_TYPE_0 + '</Type>'

L_PIONEER_DEVICE_0 = '\n'.join([
    L_PIONEER_DEVICE_START_0,
    L_PIONEER_UUID_0,
    L_PIONEER_COMMENT_0,
    L_PIONEER_IPV4_0,
    L_PIONEER_PORT_0,
    L_PIONEER_ROOM_NAME_0,
    L_PIONEER_ROOM_UUID_0,
    L_PIONEER_TYPE_0,
    L_DEVICE_END
])

TESTING_PIONEER_DEVICE_NAME_1 = 'Missing Device'
TESTING_PIONEER_DEVICE_KEY_1 = '0'
TESTING_PIONEER_DEVICE_ACTIVE_1 = 'True'
TESTING_PIONEER_DEVICE_UUID_1 = 'Pioneer.-0001-0000-0000-0123456789ab'
TESTING_PIONEER_DEVICE_COMMENT_1 = 'VSX-822-K Bogus'
TESTING_PIONEER_DEVICE_IPV4_1 = '192.168.1.122'
TESTING_PIONEER_DEVICE_PORT_1 = '8102'
TESTING_PIONEER_DEVICE_ROOM_NAME_1 = 'Master Bedroom'
TESTING_PIONEER_DEVICE_ROOM_UUID_1 = 'Room....-0001-0000-0000-0123456789ab'
TESTING_PIONEER_DEVICE_TYPE_1 = 'Fake Receiver'

L_PIONEER_DEVICE_START_1 = '    ' + \
    '<' + TESTING_DEVICE + \
    ' Name="' + TESTING_PIONEER_DEVICE_NAME_1 + \
    '" Key="' + TESTING_PIONEER_DEVICE_KEY_1 + \
    '" Active="' + TESTING_PIONEER_DEVICE_ACTIVE_1 + \
    '">'
L_PIONEER_UUID_1 = '<UUID>' + TESTING_PIONEER_DEVICE_UUID_1 + '</UUID>'
L_PIONEER_COMMENT_1 = '<Comment>' + TESTING_PIONEER_DEVICE_COMMENT_1 + '</Comment>'
L_PIONEER_IPV4_1 = '<IPv4>' + TESTING_PIONEER_DEVICE_IPV4_1 + '</IPv4>'
L_PIONEER_PORT_1 = '<Port>' + TESTING_PIONEER_DEVICE_PORT_1 + '</Port>'
L_PIONEER_ROOM_NAME_1 = '<RoomName>' + TESTING_PIONEER_DEVICE_ROOM_NAME_1 + '</RoomName>'
L_PIONEER_ROOM_UUID_1 = '<RoomUUID>' + TESTING_PIONEER_DEVICE_ROOM_UUID_1 + '</RoomUUID>'
L_PIONEER_TYPE_1 = '<Type>' + TESTING_PIONEER_DEVICE_TYPE_1 + '</Type>'

L_PIONEER_DEVICE_1 = '\n'.join([
    L_PIONEER_DEVICE_START_1,
    L_PIONEER_UUID_1,
    L_PIONEER_COMMENT_1,
    L_PIONEER_IPV4_1,
    L_PIONEER_PORT_1,
    L_PIONEER_ROOM_NAME_1,
    L_PIONEER_ROOM_UUID_1,
    L_PIONEER_TYPE_1,
    L_DEVICE_END
])

XML_PIONEER_SECTION = '\n'.join([
    L_PIONEER_SECTION_START,
    L_PIONEER_DEVICE_0,
    L_PIONEER_DEVICE_1,
    L_PIONEER_SECTION_END
])

# ## END DBK
