"""
@name:      PyHouse/src/Modules/Housing/Entertainment/pandora/test/xml_pandora.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2018-2018 by D. Brian Kimmel
@note:      Created on Aug 03, 2018
@license:   MIT License
@summary:

"""

__updated__ = '2018-08-08'

TESTING_PANDORA_SECTION = 'PandoraSection'
TESTING_PANDORA_DEVICE = 'Device'
TESTING_CONNECTION = 'Connection'
TESTING_PANDORA_ACTIVE = 'True'

L_PANDORA_SECTION_START = '<' + TESTING_PANDORA_SECTION + ' Active="' + TESTING_PANDORA_ACTIVE + '">'
L_PANDORA_SECTION_END = '</' + TESTING_PANDORA_SECTION + '>'
L_PANDORA_DEVICE_END = '</' + TESTING_PANDORA_DEVICE + '>'

TESTING_PANDORA_DEVICE_NAME_0 = 'On pi-06-ct '
TESTING_PANDORA_DEVICE_KEY_0 = '0'
TESTING_PANDORA_DEVICE_ACTIVE_0 = 'True'
TESTING_PANDORA_DEVICE_COMMENT_0 = 'Living Room'
TESTING_PANDORA_DEVICE_COMPUTER_0 = '192.168.9.16'
TESTING_PANDORA_CONNECTION_DEVICE_0_0 = 'Pioneer'
TESTING_PANDORA_CONNECTION_INPUT_NAME_0_0 = 'CD'
TESTING_PANDORA_CONNECTION_INPUT_CODE_0_0 = '01FN'

L_PANDORA_DEVICE_START_0 = \
    '<' + TESTING_PANDORA_DEVICE + \
    ' Name="' + TESTING_PANDORA_DEVICE_NAME_0 + \
    '" Key="' + TESTING_PANDORA_DEVICE_KEY_0 + \
    '" Active="' + TESTING_PANDORA_DEVICE_ACTIVE_0 + \
    '">'
L_PANDORA_COMMENT_0 = '<Comment>' + TESTING_PANDORA_DEVICE_COMMENT_0 + '</Comment>'
L_PANDORA_COMPUTER_0 = '<Computer>' + TESTING_PANDORA_DEVICE_COMPUTER_0 + '</Computer>'
L_PANDORA_CONNECTION_DEVICE_0 = '<Connection>' + TESTING_PANDORA_CONNECTION_DEVICE_0_0 + '</Connection>'
L_PANDORA_CONNECTION_INPUT_NAME_0 = '<InputName>' + TESTING_PANDORA_CONNECTION_INPUT_NAME_0_0 + '</InputName>'
L_PANDORA_CONNECTION_INPUT_CODE_0 = '<InputCode>' + TESTING_PANDORA_CONNECTION_INPUT_CODE_0_0 + '</InputCode>'

L_PANDORA_DEVICE_0 = '\n'.join([
    L_PANDORA_DEVICE_START_0,
    L_PANDORA_COMMENT_0,
    L_PANDORA_COMPUTER_0,
    L_PANDORA_CONNECTION_DEVICE_0,
    L_PANDORA_CONNECTION_INPUT_NAME_0,
    L_PANDORA_CONNECTION_INPUT_CODE_0,
    L_PANDORA_DEVICE_END
])

XML_PANDORA_SECTION = '\n'.join([
    L_PANDORA_SECTION_START,
    L_PANDORA_DEVICE_0,
    L_PANDORA_SECTION_END
])

# ## END DBK
