---
# Name:      PyHouse/Project/admin/config/Yaml/pandora.yaml
# Author:    D. Brian Kimmel
# Contact:   D.BrianKimmel@gmail.com
# Copyright: (c)2019-2019 by D. Brian Kimmel
# Created:   Jun  7, 2019
# Updated:   Jul  1, 2019
# License:   MIT License
# Summary:   This is for pandora.

Pandora:
  Name: Pandora service
  Active: 'True'
  Comment: The Pandora music service
  LastActive: 2001-01-01 01:02:03

  Service:

    - Name: Primary
      Active: 'true'
      Comment: main connection
      MaxSessions: 1
      Host:
        Name: pandora-ct
        Port: None
        IPv4: 192.168.9.16
        IPv6: None
      Connection:
        Type: wire
        Family: Pioneer
        Model: VSX-833-K
        InputName: CD
      Login:
        Name: d.briankimmel@gmail.com
        Password: !Secret1 encripted

    - Name: Downstairs
      Active: 'false'
      Comment: for music downstairs
      MaxSessions: 1
      Host:
        Name: pi-02-ct
      Connection:
        Type: bluetooth
        Family: xxx
        Model: none
        InputName: bluetooth
      Login:
        Name: map
        Password: !Secret2

### END DBK
