"""
@name:      PyHouse/src/Modules/Irrigation/test/xml_irrigation.py
@author:    D. Brian Kimmel
@contact:   D.BrianKimmel@gmail.com
@copyright: (c) 2015-2016 by D. Brian Kimmel
@license:   MIT License
@note:      Created on Jun 30, 2015
@Summary:

"""

__updated__ = '2016-08-18'

L_IRRIGATION_SECTION_START = '<IrrigationSection>'
L_IRRIGATION_SECTION_END = '</IrrigationSection>'
L_IRRIGATION_SYSTEM_END = '</IrrigationSystem>'
L_IRRIGATION_ZONE_END = '</Zone>'

TESTING_IRRIGATION_SYSTEM_NAME_0 = 'LawnSystem'
TESTING_IRRIGATION_SYSTEM_KEY_0 = '0'
TESTING_IRRIGATION_SYSTEM_ACTIVE_0 = 'True'
TESTING_IRRIGATION_SYSTEM_UUID_0 = 'Irrigate-0000-0000-0000-0123456789ab'
TESTING_IRRIGATION_SYSTEM_COMMENT_0 = 'Main yard system with Well Relay and 13 zones'

L_IRRIGATION_SYSTEM_START_0 = '<IrrigationSystem Name="' + TESTING_IRRIGATION_SYSTEM_NAME_0 + \
        '" Key="' + TESTING_IRRIGATION_SYSTEM_KEY_0 + \
        '" Active="' + TESTING_IRRIGATION_SYSTEM_ACTIVE_0 + \
        '">'
L_IRRIGATION_SYSTEM_UUID_0 = '<UUID>' + TESTING_IRRIGATION_SYSTEM_UUID_0 + '</UUID>'
L_IRRIGATION_SYSTEM_COMMENT_0 = '<Comment>' + TESTING_IRRIGATION_SYSTEM_COMMENT_0 + '</Comment>'

# Zone 0
TESTING_IRRIGATION_ZONE_NAME_0_0 = 'Front Rotors # 1'
TESTING_IRRIGATION_ZONE_KEY_0_0 = '0'
TESTING_IRRIGATION_ZONE_ACTIVE_0_0 = 'True'
TESTING_IRRIGATION_ZONE_UUID_0_0 = 'Irrigate-Zone-0000-0000-0123456789ab'
TESTING_IRRIGATION_ZONE_COMMENT_0_0 = 'Rotors on the West corner of the yard'
TESTING_IRRIGATION_ZONE_DURATION_0_0 = '2700'

L_IRRIGATION_ZONE_START_0_0 = '<Zone Name="' + TESTING_IRRIGATION_ZONE_NAME_0_0 + \
        '" Key="' + TESTING_IRRIGATION_ZONE_KEY_0_0 + \
        '" Active="' + TESTING_IRRIGATION_ZONE_ACTIVE_0_0 + \
        '">'
L_IRRIGATION_ZONE_UUID_0_0 = '<UUID>' + TESTING_IRRIGATION_ZONE_UUID_0_0 + '</UUID>'
L_IRRIGATION_ZONE_COMMENT_0_0 = '<Comment>' + TESTING_IRRIGATION_ZONE_COMMENT_0_0 + '</Comment>'
L_IRRIGATION_ZONE_DURATION_0_0 = '<Duration>' + TESTING_IRRIGATION_ZONE_DURATION_0_0 + '</Duration>'

L_IRRIGATION_ZONE_0_0 = '\n'.join([
    L_IRRIGATION_ZONE_START_0_0,
    L_IRRIGATION_ZONE_UUID_0_0,
    L_IRRIGATION_ZONE_COMMENT_0_0,
    L_IRRIGATION_ZONE_DURATION_0_0,
    L_IRRIGATION_ZONE_END
])

# Zone 1
TESTING_IRRIGATION_ZONE_NAME_0_1 = 'Front Rotors # 2'
TESTING_IRRIGATION_ZONE_KEY_0_1 = '1'
TESTING_IRRIGATION_ZONE_ACTIVE_0_1 = 'True'
TESTING_IRRIGATION_ZONE_UUID_0_1 = 'Irrigate-Zone-0001-0001-0123456789ab'
TESTING_IRRIGATION_ZONE_COMMENT_0_1 = 'Rotors on the Driveway side of the yard'
TESTING_IRRIGATION_ZONE_DURATION_0_1 = '2700'

L_IRRIGATION_ZONE_START_0_1 = '<Zone Name="' + TESTING_IRRIGATION_ZONE_NAME_0_1 + \
        '" Key="' + TESTING_IRRIGATION_ZONE_KEY_0_1 + \
        '" Active="' + TESTING_IRRIGATION_ZONE_ACTIVE_0_1 + \
        '">'
L_IRRIGATION_ZONE_UUID_0_1 = '<UUID>' + TESTING_IRRIGATION_ZONE_UUID_0_1 + '</UUID>'
L_IRRIGATION_ZONE_COMMENT_0_1 = '<Comment>' + TESTING_IRRIGATION_ZONE_COMMENT_0_1 + '</Comment>'
L_IRRIGATION_ZONE_DURATION_0_1 = '<Duration>' + TESTING_IRRIGATION_ZONE_DURATION_0_1 + '</Duration>'

L_IRRIGATION_ZONE_0_1 = '\n'.join([
    L_IRRIGATION_ZONE_START_0_1,
    L_IRRIGATION_ZONE_UUID_0_1,
    L_IRRIGATION_ZONE_COMMENT_0_1,
    L_IRRIGATION_ZONE_DURATION_0_1,
    L_IRRIGATION_ZONE_END
])

L_IRRIGATION_SYSTEM_0 = '\n'.join([
    L_IRRIGATION_SYSTEM_START_0,
    L_IRRIGATION_SYSTEM_UUID_0,
    L_IRRIGATION_SYSTEM_COMMENT_0,
    L_IRRIGATION_ZONE_0_0,
    L_IRRIGATION_ZONE_0_1,
    L_IRRIGATION_SYSTEM_END
])

TESTING_IRRIGATION_SYSTEM_NAME_1 = 'Lanai Drip'
TESTING_IRRIGATION_SYSTEM_KEY_1 = '1'
TESTING_IRRIGATION_SYSTEM_ACTIVE_1 = 'True'
TESTING_IRRIGATION_SYSTEM_UUID_1 = 'Irrigate-0001-0001-0001-0123456789ab'

L_IRRIGATION_SYSTEM_START_1 = '<IrrigationSystem Name="' + TESTING_IRRIGATION_SYSTEM_NAME_1 + \
        '" Key="' + TESTING_IRRIGATION_SYSTEM_KEY_1 + \
        '" Active="' + TESTING_IRRIGATION_SYSTEM_ACTIVE_1 + \
        '">'
L_IRRIGATION_SYSTEM_UUID_1 = '<UUID>' + TESTING_IRRIGATION_SYSTEM_UUID_1 + '</UUID>'


# Zone 0
TESTING_IRRIGATION_ZONE_NAME_1_0 = 'Front Rotors # 1'
TESTING_IRRIGATION_ZONE_KEY_1_0 = '0'
TESTING_IRRIGATION_ZONE_ACTIVE_1_0 = 'True'
TESTING_IRRIGATION_ZONE_UUID_1_0 = 'Irrigate-Zone-0000-0000-0123456789ab'
TESTING_IRRIGATION_ZONE_COMMENT_1_0 = 'Rotors on the West corner of the yard'
TESTING_IRRIGATION_ZONE_DURATION_1_0 = '2700'

L_IRRIGATION_ZONE_START_1_0 = '<Zone Name="' + TESTING_IRRIGATION_ZONE_NAME_1_0 + \
        '" Key="' + TESTING_IRRIGATION_ZONE_KEY_1_0 + \
        '" Active="' + TESTING_IRRIGATION_ZONE_ACTIVE_1_0 + \
        '">'
L_IRRIGATION_ZONE_UUID_1_0 = '<UUID>' + TESTING_IRRIGATION_ZONE_UUID_1_0 + '</UUID>'
L_IRRIGATION_ZONE_COMMENT_1_0 = '<Comment>' + TESTING_IRRIGATION_ZONE_COMMENT_1_0 + '</Comment>'
L_IRRIGATION_ZONE_DURATION_1_0 = '<Duration>' + TESTING_IRRIGATION_ZONE_DURATION_1_0 + '</Duration>'

L_IRRIGATION_ZONE_1_0 = '\n'.join([
    L_IRRIGATION_ZONE_START_1_0,
    L_IRRIGATION_ZONE_UUID_1_0,
    L_IRRIGATION_ZONE_COMMENT_1_0,
    L_IRRIGATION_ZONE_DURATION_1_0,
    L_IRRIGATION_ZONE_END
])

L_IRRIGATION_SYSTEM_1 = '\n'.join([
    L_IRRIGATION_SYSTEM_START_1,
    L_IRRIGATION_SYSTEM_UUID_1,
    L_IRRIGATION_ZONE_1_0,
    L_IRRIGATION_SYSTEM_END
])

# ## Irrigation System 3 - Cannon trail drip system

TESTING_IRRIGATION_SYSTEM_NAME_2 = 'Cannon Trail Drip'
TESTING_IRRIGATION_SYSTEM_KEY_2 = '2'
TESTING_IRRIGATION_SYSTEM_ACTIVE_2 = 'True'
TESTING_IRRIGATION_SYSTEM_UUID_2 = 'Irrigate-0002-0002-0002-0123456789ab'

L_IRRIGATION_SYSTEM_START_2 = '<IrrigationSystem Name="' + TESTING_IRRIGATION_SYSTEM_NAME_2 + \
        '" Key="' + TESTING_IRRIGATION_SYSTEM_KEY_2 + \
        '" Active="' + TESTING_IRRIGATION_SYSTEM_ACTIVE_2 + \
        '">'
L_IRRIGATION_SYSTEM_UUID_2 = '<UUID>' + TESTING_IRRIGATION_SYSTEM_UUID_2 + '</UUID>'


# Zone 0
TESTING_IRRIGATION_ZONE_NAME_2_0 = 'Front Drip # 1'
TESTING_IRRIGATION_ZONE_KEY_2_0 = '0'
TESTING_IRRIGATION_ZONE_ACTIVE_2_0 = 'True'
TESTING_IRRIGATION_ZONE_UUID_2_0 = 'Irrigate-0002-0000-0000-0123456789ab'
TESTING_IRRIGATION_ZONE_COMMENT_2_0 = 'xxx'
TESTING_IRRIGATION_ZONE_DURATION_2_0 = '2700'

L_IRRIGATION_ZONE_START_2_0 = '<Zone Name="' + TESTING_IRRIGATION_ZONE_NAME_2_0 + \
        '" Key="' + TESTING_IRRIGATION_ZONE_KEY_2_0 + \
        '" Active="' + TESTING_IRRIGATION_ZONE_ACTIVE_2_0 + \
        '">'
L_IRRIGATION_ZONE_UUID_2_0 = '<UUID>' + TESTING_IRRIGATION_ZONE_UUID_2_0 + '</UUID>'
L_IRRIGATION_ZONE_COMMENT_2_0 = '<Comment>' + TESTING_IRRIGATION_ZONE_COMMENT_2_0 + '</Comment>'
L_IRRIGATION_ZONE_DURATION_2_0 = '<Duration>' + TESTING_IRRIGATION_ZONE_DURATION_2_0 + '</Duration>'

L_IRRIGATION_ZONE_2_0 = '\n'.join([
    L_IRRIGATION_ZONE_START_2_0,
    L_IRRIGATION_ZONE_UUID_2_0,
    L_IRRIGATION_ZONE_COMMENT_2_0,
    L_IRRIGATION_ZONE_DURATION_2_0,
    L_IRRIGATION_ZONE_END
])

L_IRRIGATION_SYSTEM_2 = '\n'.join([
    L_IRRIGATION_SYSTEM_START_2,
    L_IRRIGATION_SYSTEM_UUID_2,
    L_IRRIGATION_ZONE_2_0,
    L_IRRIGATION_SYSTEM_END
])

# ## The final irrigation section

XML_IRRIGATION = '\n'.join([
    L_IRRIGATION_SECTION_START,
    L_IRRIGATION_SYSTEM_0,
    L_IRRIGATION_SYSTEM_1,
    L_IRRIGATION_SYSTEM_2,
    L_IRRIGATION_SECTION_END
])


_IRRIGATION_XSD = """
<xs:schema
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="IrrigationSection">
  </xs:element>

</xs:schema>
"""
# ## END DBK
