# Name:      PyHouse/Project/admin/config/Yaml/entertainment.yaml
# Author:    D. Brian Kimmel
# Contact:   D.BrianKimmel@gmail.com
# Copyright: (c)2019-2019 by D. Brian Kimmel
# Created:   Jun 30, 2019
# Updated:   Jun 30, 2019
# License:   MIT License
# Summary:   This is for PyHouse

Entertainment:
  Services:
    - Pandora: !include pandora.yaml
  Devices:
    - Pioneer: !include pioneer.yaml
    - Samsung: !include samsung.yaml

### END DBK
