# Name:      PyHouse/Project/admin/config/Yaml/computer/mqtt.yaml
# Author:    D. Brian Kimmel
# Contact:   D.BrianKimmel@gmail.com
# Copyright: (c)2019-2019 by D. Brian Kimmel
# Created:   Jun 19, 2019
# Updated:   Jun 19, 2019
# License:   MIT License
# Summary:   This is for PyHouse
---

Mqtt:
   - Broker:
      Name: Cannon Trail
      Active: 'true'
      Comment: For Cannon Trail (if reachable)
      LastUpdate: 2019-05-18 12:41:20.061260
      UUID: 92c6466-5852-11e7-8389-801f02b5e4e6
      BrokerHost: mqtt-ct
      BrokerPort: 1883
      BrokerUser: None
      BrokerPassword: None
      Class: Local

#   - Broker:
#      Name: Local Laptop
#      Active: 'true'
#      Comment: For testing so we have a local broker
#      LastUpdate: 2019-05-18 12:41:20.061260
#      UUID: 392c6466-5852-11e7-8389-801f02b5e4e6
#      BrokerHost: localhost
#      BrokerPort: 1883
#      BrokerUser: None
#      BrokerPassword: None
#      Class: Local

### END DBK
